# Generated by Django 4.2.3 on 2023-07-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0002_ms_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ms_user',
            old_name='text',
            new_name='contact',
        ),
    ]
