# Generated by Django 4.2.3 on 2023-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0005_data_from_name_alter_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ms_user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/user_image'),
        ),
    ]
