# Generated by Django 4.2.3 on 2023-07-20 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0004_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('like_range', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='dont like.'), django.core.validators.MaxValueValidator(5, message='like.')])),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopsite.product')),
            ],
        ),
    ]
