# Generated by Django 4.2.3 on 2023-07-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0009_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
