# Generated by Django 4.2.3 on 2023-07-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0010_remove_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='coment',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
