# Generated by Django 4.2.3 on 2023-07-22 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0012_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsite.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopsite.product')),
            ],
            options={
                'db_table': 'OrderItem2',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(null=True, through='shopsite.OrderItem', to='shopsite.product'),
        ),
    ]
