# Generated by Django 4.2.3 on 2023-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopsite', '0014_alter_like_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/image'),
        ),
    ]
